pipeline {
    agent { label 'Jenkins-Agent' }

    environment {
        DOCKER_HUB_REPO = 'narendransekar'
        DOCKER_CREDENTIALS_ID  = 'docker-hub-credentials-id' // Jenkins credential ID for Docker Hub
		AZURE_CREDENTIALS = 'azure-credentials-id'
        AZURE_WEB_APP = 'myjenkinswebapp'
        RESOURCE_GROUP = 'jenkinsresourcegroup'
		
    }

    stages {
        stage('Clone Repository') {
            steps {
                // Clone your .NET Core project repository
                git 'https://github.com/narendransekar7/Support.git'
            }
        }
		
		stage('Build Docker Images') {
            parallel {
                stage('Build SS.Auth.Server.API') {
                    steps {
					    script {
                            dir('SupportSystemManagement/SupportSystem/SS.Auth.Server.API') {
                                sh 'docker build -t ${DOCKER_HUB_REPO}/ss-auth-server-api:latest .'
                            }
                        }
                    }
				}
				stage('Build SS.Gateway.API') {
					steps {
					    script {
                            dir('SupportSystemManagement/SupportSystem/SS.Gateway.API') {
                                sh 'docker build -t ${DOCKER_HUB_REPO}/ss-gateway-api:latest .'
                            }
                        }
                    }
				}
				stage('Build SupportSystem.ReactUI') {
					steps {
					    script {
                            dir('SupportSystemManagement/SupportSystem/supportsystem.reactui') {
                                sh 'docker build -t ${DOCKER_HUB_REPO}/ss-react-ui:latest .'
                            }
                        }
                    }
				}
				stage('Build SupportSystem.WebAPI') {
					steps {
					    script {
                            dir('SupportSystemManagement/SupportSystem') {
                                sh 'docker build -t ${DOCKER_HUB_REPO}/ss-web-api:latest .'
                            }
                        }
                    }
				}
            }
        }
		
		stage('Push Docker Images') {
            steps {
                script {
                    // Login to Docker Hub
                    withCredentials([usernamePassword(credentialsId: DOCKER_CREDENTIALS_ID, usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
                    }

                    // Push the Docker image to Docker Hub
                    sh 'docker push ${DOCKER_HUB_REPO}/ss-auth-server-api:latest'
					sh 'docker push ${DOCKER_HUB_REPO}/ss-gateway-api:latest'
                    sh 'docker push ${DOCKER_HUB_REPO}/ss-react-ui:latest'
					sh 'docker push ${DOCKER_HUB_REPO}/ss-web-api:latest'
                }
            }
        }
		
        stage('Deploy to Azure Web App') {
            steps {
                script {
				
					dir('SupportSystemManagement/SupportSystem') {
						// Validate the docker-compose.yml file exists
						if (!fileExists('docker-compose.yml')) {
							error 'docker-compose.yml file not found in the repository!'
						}

						withCredentials([azureServicePrincipal(credentialsId: AZURE_CREDENTIALS)]) {
							sh """
								az webapp config container set \
									--name ${AZURE_WEB_APP} \
									--resource-group ${RESOURCE_GROUP} \
									--multicontainer-config-type compose \
									--multicontainer-config-file docker-compose.yml
								az webapp restart --name ${AZURE_WEB_APP} --resource-group ${RESOURCE_GROUP}
							"""
						}

						 
						 
                    }

                }
            }
        }
		
    }
     


}
