pipeline {
    agent { label 'Jenkins-Agent' }

    environment {
        DOCKER_HUB_REPO = 'narendransekar'
        DOCKER_CREDENTIALS_ID  = 'docker-hub-credentials-id' // Jenkins credential ID for Docker Hub
        AZURE_APP_NAME = 'myjenkinswebapp'
        AZURE_RG = 'mywebapp'
    }

    stages {
        stage('Clone Repository') {
            steps {
                // Clone your .NET Core project repository
                git 'https://github.com/narendransekar7/Support.git'
            }
        }
		
		stage('Build Docker Images') {
            parallel {
                stage('Build SS.Auth.Server.API') {
                    steps {
					    script {
                            dir('SupportSystemManagement/SupportSystem/SS.Auth.Server.API') {
                                sh 'docker build -t ${DOCKER_HUB_REPO}/ss-auth-server-api:latest .'
                            }
                        }
                    }
                }
            }
        }
		
		stage('Push Docker Images') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', DOCKER_CREDENTIALS_ID) {
                        sh "docker push ${DOCKER_HUB_REPO}/ss-auth-server-api:latest"
                    }
                }
            }
        }
		
    }
     


}
